# Generated by Django 4.1.3 on 2022-11-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Diagnos', models.CharField(max_length=70, verbose_name='Диангоз')),
                ('Severity', models.IntegerField(verbose_name='Степень тяжести')),
            ],
            options={
                'verbose_name': 'Диагноз',
                'verbose_name_plural': 'Диагнозы',
            },
        ),
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamePac', models.CharField(max_length=70, verbose_name='Имя пациента')),
                ('Policy', models.CharField(max_length=16, verbose_name='Номер полиса')),
                ('Birth', models.DateField(verbose_name='Дата рождения')),
                ('Location', models.CharField(max_length=70, verbose_name='Адресс проживания')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MethodOfThreatment', models.CharField(max_length=70, verbose_name='Метод лечения')),
                ('DurationOfTreat', models.CharField(max_length=70, verbose_name='Время лечения')),
            ],
            options={
                'verbose_name': 'Лечение',
                'verbose_name_plural': 'Лечение',
            },
        ),
    ]
