# Generated by Django 4.1.3 on 2022-11-27 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatment',
            options={'verbose_name': 'Лечение', 'verbose_name_plural': 'Способы лечения'},
        ),
    ]
