# Generated by Django 4.1.3 on 2022-11-30 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_alter_treatment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='diag_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.pacient', verbose_name='Номер полиса'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='treat_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.pacient', verbose_name='Номер полиса'),
        ),
    ]
